// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUh_46ONjZQFAQ5LfxHeIEQZwN4GPrg1k',
    appId: '1:234813610744:web:637c180570b477471db90d',
    messagingSenderId: '234813610744',
    projectId: 'gymnastics-analysis-543bc',
    authDomain: 'gymnastics-analysis-543bc.firebaseapp.com',
    storageBucket: 'gymnastics-analysis-543bc.appspot.com',
    measurementId: 'G-HV4CTRY5QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlLc2UEX-IguRLnTjuwp5wAfm3kedejgA',
    appId: '1:234813610744:android:fb4a3b5e1f1739441db90d',
    messagingSenderId: '234813610744',
    projectId: 'gymnastics-analysis-543bc',
    storageBucket: 'gymnastics-analysis-543bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFm_uqwq-oeXD77df6FV8uBxoewe_k_hk',
    appId: '1:234813610744:ios:a737b8870289e2bb1db90d',
    messagingSenderId: '234813610744',
    projectId: 'gymnastics-analysis-543bc',
    storageBucket: 'gymnastics-analysis-543bc.appspot.com',
    iosClientId: '234813610744-79jkbtnuqr3327h8b72m7ll686vv1ie6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymnasticsAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFm_uqwq-oeXD77df6FV8uBxoewe_k_hk',
    appId: '1:234813610744:ios:9fed7525906666cd1db90d',
    messagingSenderId: '234813610744',
    projectId: 'gymnastics-analysis-543bc',
    storageBucket: 'gymnastics-analysis-543bc.appspot.com',
    iosClientId: '234813610744-npdbeo7k8kmpg7b1mrmmojdug5totctq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymnasticsAnalysis.RunnerTests',
  );
}
